<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Milkman Cycle with Real Rotating Wheels _67fd96</name>
   <tag></tag>
   <elementGuidId>6446e53c-fec7-4749-9cc1-8de5522d8678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-5694.status-publish.instock.product_cat-collectibles.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-variable > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > h2.woocommerce-loop-product__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dswbm-sliders-28180']/div[2]/div/ul/li[9]/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5975d569-96eb-4e2c-b744-36c6f5af45e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-loop-product__title</value>
      <webElementGuid>0af38eba-d96b-49bd-909d-219dd37a9f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Milkman Cycle with Real Rotating Wheels Antique Metal Wooden Showpiece Miniature for Living Room Table Top | Toy for Kids and Home Decor Gifts</value>
      <webElementGuid>a33c6f55-22c7-4165-a1f8-2c2108f18bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dswbm-sliders-28180&quot;)/div[@class=&quot;bx-wrapper&quot;]/div[@class=&quot;bx-viewport&quot;]/ul[@class=&quot;wbm-slider products&quot;]/li[@class=&quot;product type-product post-5694 status-publish instock product_cat-collectibles has-post-thumbnail sale taxable shipping-taxable purchasable product-type-variable&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/h2[@class=&quot;woocommerce-loop-product__title&quot;]</value>
      <webElementGuid>2995224d-09b3-4ded-8de8-05e16d5cfd3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dswbm-sliders-28180']/div[2]/div/ul/li[9]/a/h2</value>
      <webElementGuid>f660f3a4-37c5-4e1f-b384-facab52574dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/h2</value>
      <webElementGuid>ab438462-dd7d-4b8c-a99e-2423e8901f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Milkman Cycle with Real Rotating Wheels Antique Metal Wooden Showpiece Miniature for Living Room Table Top | Toy for Kids and Home Decor Gifts' or . = 'Milkman Cycle with Real Rotating Wheels Antique Metal Wooden Showpiece Miniature for Living Room Table Top | Toy for Kids and Home Decor Gifts')]</value>
      <webElementGuid>ae14eebe-2ad1-4c4a-ab4c-e97fa6330c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
