<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_category_banner_image</name>
   <tag></tag>
   <elementGuidId>4283a5fd-f73d-4064-a528-7741bc3dceaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.category_banner_image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ceee3ea1-58a3-4224-85ab-f5ba88827d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg</value>
      <webElementGuid>4fc71f6a-52ec-4757-a675-f71c04be7a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category_banner_image</value>
      <webElementGuid>0309f04b-e69e-49ee-bc4a-17d53e152bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;col-full&quot;]/div[@class=&quot;wbm_banner_image banner&quot;]/img[@class=&quot;category_banner_image&quot;]</value>
      <webElementGuid>7ec6bd63-bd26-40c6-b5cd-d18efe2d042b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/img</value>
      <webElementGuid>1dc85d92-15ac-4f34-923a-a3358aef155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg')]</value>
      <webElementGuid>9028d962-3bcb-4913-bae6-12a3d37098c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>bdf70af1-395c-4701-b5f7-60237e5d6f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg']</value>
      <webElementGuid>b59fca0c-cb38-40c4-8a1f-1a112ea83732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
