<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lamps  Lightings</name>
   <tag></tag>
   <elementGuidId>dbe5eae9-b846-461e-9aaf-46712fc806cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26694 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26694']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49338d2a-41cf-4080-a28c-86574138f2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/lamps-lightings/</value>
      <webElementGuid>7c0a7fad-8222-41b1-8eb9-d3f18d6f6bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lamps &amp; Lightings</value>
      <webElementGuid>d85fb66a-aed3-47c0-be49-e5250db99f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26694&quot;)/a[1]</value>
      <webElementGuid>b56940bd-c8a4-47be-84c9-fbdab03f530b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26694']/a</value>
      <webElementGuid>1a9318cb-adb5-4f78-a42b-1c9aea502fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lamps &amp; Lightings')]</value>
      <webElementGuid>b6820009-5018-4872-816e-9a315e806459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/lamps-lightings/')]</value>
      <webElementGuid>e9c9c1c2-885d-44f7-bf9f-ea02977ce0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/a</value>
      <webElementGuid>1097c1d9-5d1a-4430-84cd-7845b9777126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/lamps-lightings/' and (text() = 'Lamps &amp; Lightings' or . = 'Lamps &amp; Lightings')]</value>
      <webElementGuid>c9ab9819-b830-4695-9b54-b78db59c7d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
