<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Handcrafts clock metal is an online store_db7054</name>
   <tag></tag>
   <elementGuidId>be85dad1-ed2e-4c40-85b7-7c5cc672765b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.term-description > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1e5b53e2-c455-4f36-ba4a-0b652ffd0dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Handcrafts clock metal is an online store that offers the latest antique-styled wall and table clocks. They come in a variety of trendy designs that will add grace to any room in your home or office. Get them at the cheapest price today.</value>
      <webElementGuid>251b8dab-b090-4e03-aaf8-d1afaacdbbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;term-description&quot;]/div[@class=&quot;term-description&quot;]/p[1]</value>
      <webElementGuid>f862310c-e763-4089-a213-71c17e2b10fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div/p</value>
      <webElementGuid>f6015e1d-d92c-4137-8aef-b8d9fe501689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/p</value>
      <webElementGuid>1b9017ff-b117-4987-b71e-0565afad2ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Handcrafts clock metal is an online store that offers the latest antique-styled wall and table clocks. They come in a variety of trendy designs that will add grace to any room in your home or office. Get them at the cheapest price today.' or . = 'Handcrafts clock metal is an online store that offers the latest antique-styled wall and table clocks. They come in a variety of trendy designs that will add grace to any room in your home or office. Get them at the cheapest price today.')]</value>
      <webElementGuid>4e80166d-4825-4f1f-ba7c-07c2f1da73e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
