<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We offer an extensive selection of hand_2ca61d</name>
   <tag></tag>
   <elementGuidId>ab115918-8d1b-4b00-99e6-89e9c29418bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.term-description > div.term-description > div.term-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>64f7e310-c6fc-454f-ab00-3494cee75089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>term-description</value>
      <webElementGuid>da9b1569-f693-4393-899f-4d26783c52cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We offer an extensive selection of handicraft items for tables, shelves, and decor, such as table-top showpieces and figurines made of wrought iron and wood. These high-quality, colorfully designed products will add a touch of royalty to any space. They are handcrafted by skilled artisans and make perfect gifts or home decor items</value>
      <webElementGuid>ce282ea6-b76d-449a-b931-560c698684b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;term-description&quot;]/div[@class=&quot;term-description&quot;]/div[@class=&quot;term-description&quot;]</value>
      <webElementGuid>743fa98f-25a3-47de-a420-96775cd9317f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div/div</value>
      <webElementGuid>812fb5f3-ec34-46c5-8587-780b68c3f980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/header/div/div/div</value>
      <webElementGuid>1a0debec-8171-4b2f-8f87-95ce5aa33d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'We offer an extensive selection of handicraft items for tables, shelves, and decor, such as table-top showpieces and figurines made of wrought iron and wood. These high-quality, colorfully designed products will add a touch of royalty to any space. They are handcrafted by skilled artisans and make perfect gifts or home decor items' or . = 'We offer an extensive selection of handicraft items for tables, shelves, and decor, such as table-top showpieces and figurines made of wrought iron and wood. These high-quality, colorfully designed products will add a touch of royalty to any space. They are handcrafted by skilled artisans and make perfect gifts or home decor items')]</value>
      <webElementGuid>1387c96a-8222-41d5-ae32-65acd4cb1972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
