<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Explore our wide range of products and di_f20893</name>
   <tag></tag>
   <elementGuidId>cf83b02f-d8c9-489c-81f6-383777f18df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.term-description > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>32087ad4-6c7e-4e18-9747-0d18eafb8e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Explore our wide range of products and discover your perfect gift for your loved ones. We offer a wide variety of metal wall decor products to choose as a perfect gift. Our collection includes wall arts, Wall hanging, shelves, home decor, frames, and much more. Our products are made of high quality metal, handcrafted with traditional ethnic looks and multi-colours.</value>
      <webElementGuid>d6082a82-9cd5-48ab-8853-9afd73c8547a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;term-description&quot;]/div[@class=&quot;term-description&quot;]/p[1]</value>
      <webElementGuid>b8255f2f-a2a2-4a46-97f7-3c0dd9f4358a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div/p</value>
      <webElementGuid>c9670279-4a5f-45c0-97de-915f2ae6f521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/p</value>
      <webElementGuid>55776a6a-7a53-4dc8-99bf-869e4c6b9096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Explore our wide range of products and discover your perfect gift for your loved ones. We offer a wide variety of metal wall decor products to choose as a perfect gift. Our collection includes wall arts, Wall hanging, shelves, home decor, frames, and much more. Our products are made of high quality metal, handcrafted with traditional ethnic looks and multi-colours.' or . = 'Explore our wide range of products and discover your perfect gift for your loved ones. We offer a wide variety of metal wall decor products to choose as a perfect gift. Our collection includes wall arts, Wall hanging, shelves, home decor, frames, and much more. Our products are made of high quality metal, handcrafted with traditional ethnic looks and multi-colours.')]</value>
      <webElementGuid>d99ff6fe-7320-4c54-8fbb-4c47ed61eacb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
