<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Musical Showpiece</name>
   <tag></tag>
   <elementGuidId>6169aec5-bfd6-4811-b6d0-edca1ca987e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26679 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Musical Showpiece')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f847b37e-6d02-42fe-901f-3adfad89c622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/musical-showpiece/</value>
      <webElementGuid>6517078e-17f2-4acf-b5dc-077a8c30a39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Musical Showpiece</value>
      <webElementGuid>9acd3b59-4883-48f0-a8aa-49c6b439b602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26679&quot;)/a[1]</value>
      <webElementGuid>93133e79-d817-4915-b9b1-798f1cc16832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26679']/a</value>
      <webElementGuid>12e43cd4-d983-4627-a9da-3347c9466d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d0a2508e-0ea8-4246-9d60-36afa79bb49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/musical-showpiece/')]</value>
      <webElementGuid>024ff689-b7cb-4d86-8b95-c7b1ad99b111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li/a</value>
      <webElementGuid>299b12b9-047b-4405-b8f0-a0419b0c66b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/musical-showpiece/' and (text() = 'Musical Showpiece' or . = 'Musical Showpiece')]</value>
      <webElementGuid>ad1f5d00-f2e0-43e6-ab0c-eaf6eaf3c6c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
